### ISSUE TITLE
[Tracker] MSFDG support  for op-challenger 

### ISSUE THREAD

**Issue by pochenai** [ethstorage/optimism#78]
General tracking for MSFDG (multi-section fault dispute game) features proposed to be included in the op-challenger2.
- [x] copy op-challenger to op-challenger2 @dajuguan 
   - https://github.com/ethstorage/optimism/pull/79
- [x] contract call @JustXxx 
   - https://github.com/ethstorage/optimism/pull/80
- [x] dataTypes for `game、position、DA`, support fetch `nbits splitdepth、moveN、MoveRightN` in gameState @dajuguan 
   - https://github.com/ethstorage/optimism/pull/81 
- [x] getSubValues from tx's calldata @dajuguan 
   - https://github.com/ethstorage/optimism/pull/84
- [x] oracle for addLocaldata and getStepData @dajuguan 
  - https://github.com/ethstorage/optimism/pull/88
- [x] monitor L1head change, and automatically respond challenge with `attackV2` @JustXxx 
   - https://github.com/ethstorage/optimism/pull/105 
- [x] monitor L1head change, and automatically respond challenge with `stepV2` @JustXxx 
   - https://github.com/ethstorage/optimism/pull/105 
- [x] e2e test for alphabet game @dajuguan 
   - https://github.com/ethstorage/optimism/pull/105 
- [ ] e2e test for cannon:  some tests are pending
   -  https://github.com/ethstorage/optimism/pull/107/
